// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFJXyfrhCjggIVfevYxsgswktf723Fro',
    appId: '1:557086055312:web:0b97a877943eb2fe1cb115',
    messagingSenderId: '557086055312',
    projectId: 'proyecti-d802e',
    authDomain: 'proyecti-d802e.firebaseapp.com',
    storageBucket: 'proyecti-d802e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGfsosEndrJmm-q43O6HFzsOJDUGyHMI',
    appId: '1:557086055312:android:66b6a761fe438dbc1cb115',
    messagingSenderId: '557086055312',
    projectId: 'proyecti-d802e',
    storageBucket: 'proyecti-d802e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLAQysEInHb4FtWO4KVEcshtQIidcjag',
    appId: '1:557086055312:ios:0327de372ac85a0a1cb115',
    messagingSenderId: '557086055312',
    projectId: 'proyecti-d802e',
    storageBucket: 'proyecti-d802e.appspot.com',
    iosBundleId: 'com.example.reporte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLAQysEInHb4FtWO4KVEcshtQIidcjag',
    appId: '1:557086055312:ios:47d6ffdeebd71ee31cb115',
    messagingSenderId: '557086055312',
    projectId: 'proyecti-d802e',
    storageBucket: 'proyecti-d802e.appspot.com',
    iosBundleId: 'com.example.reporte.RunnerTests',
  );
}
